apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      port: 8000
      targetPort: 80
      protocol: TCP
      nodePort: 30001 #range:  > 30000 && < 32767